# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/ethereum/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    echo $(GOPATH)
    echo $(modulePath)
  displayName: 'Set up the Go workspace'

- script: |
    echo 'GOPATH=${GOPATH}'
    echo 'modulePath=${modulePath}'
    go get -u ekyu.moe/cryptonight
    go run build/ci.go install
    go run build/ci.go test -coverage
    go run build/ci.go debsrc
  workingDirectory: '$(modulePath)'
  displayName: 'build, test, package'
