name: Report Bug
description: Create a bug report.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please, provide as much details as possible to make proper evaluation and in the end resolve the bug report faster.

  - type: markdown
    attributes:
      value: |
        Software specific details.

  - type: input
    id: os
    attributes:
      label: OS and version
      description: Name and version of OS used.
      placeholder: OS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Software version
      description: Version of software used.
      placeholder: Version
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Describe the Bug.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce Bug
      description: Steps to reproduce the behavior.
      placeholder: 1. Step 1
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe the result you are expecting.
      placeholder: Result
    validations:
      required: true

  - type: input
    id: hash
    attributes:
      label: Commit hash
      description: Commit hash if known.
      placeholder: baf2aab0128f07262b564214ec70fc07befc6bb3

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Please, place additional content or screenshots.
