// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/core-coin/go-core/common"
	"github.com/core-coin/go-core/common/hexutil"
)

var _ = (*txdataMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t txdata) MarshalJSON() ([]byte, error) {
	type txdata struct {
		AccountNonce hexutil.Uint64  `json:"nonce"    gencodec:"required"`
		Price        *hexutil.Big    `json:"energyPrice" gencodec:"required"`
		EnergyLimit  hexutil.Uint64  `json:"energy"      gencodec:"required"`
		ChainID      hexutil.Uint64  `json:"chain_id" gencodec:"required"`
		Recipient    *common.Address `json:"to"       rlp:"nil"`
		Amount       *hexutil.Big    `json:"value"    gencodec:"required"`
		Payload      hexutil.Bytes   `json:"input"    gencodec:"required"`
		Signature    hexutil.Bytes   `json:"signature"    gencodec:"required"`
		Hash         *common.Hash    `json:"hash" rlp:"-"`
	}
	var enc txdata
	enc.AccountNonce = hexutil.Uint64(t.AccountNonce)
	enc.Price = (*hexutil.Big)(t.Price)
	enc.EnergyLimit = hexutil.Uint64(t.EnergyLimit)
	enc.ChainID = hexutil.Uint64(t.ChainID)
	enc.Recipient = t.Recipient
	enc.Amount = (*hexutil.Big)(t.Amount)
	enc.Payload = t.Payload
	enc.Signature = t.Signature
	enc.Hash = t.Hash
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *txdata) UnmarshalJSON(input []byte) error {
	type txdata struct {
		AccountNonce *hexutil.Uint64 `json:"nonce"    gencodec:"required"`
		Price        *hexutil.Big    `json:"energyPrice" gencodec:"required"`
		EnergyLimit  *hexutil.Uint64 `json:"energy"      gencodec:"required"`
		ChainID      *hexutil.Uint64 `json:"chain_id" gencodec:"required"`
		Recipient    *common.Address `json:"to"       rlp:"nil"`
		Amount       *hexutil.Big    `json:"value"    gencodec:"required"`
		Payload      *hexutil.Bytes  `json:"input"    gencodec:"required"`
		Signature    *hexutil.Bytes  `json:"signature"    gencodec:"required"`
		Hash         *common.Hash    `json:"hash" rlp:"-"`
	}
	var dec txdata
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.AccountNonce == nil {
		return errors.New("missing required field 'nonce' for txdata")
	}
	t.AccountNonce = uint64(*dec.AccountNonce)
	if dec.Price == nil {
		return errors.New("missing required field 'energyPrice' for txdata")
	}
	t.Price = (*big.Int)(dec.Price)
	if dec.EnergyLimit == nil {
		return errors.New("missing required field 'energy' for txdata")
	}
	t.EnergyLimit = uint64(*dec.EnergyLimit)
	if dec.ChainID == nil {
		return errors.New("missing required field 'chain_id' for txdata")
	}
	t.ChainID = uint(*dec.ChainID)
	if dec.Recipient != nil {
		t.Recipient = dec.Recipient
	}
	if dec.Amount == nil {
		return errors.New("missing required field 'value' for txdata")
	}
	t.Amount = (*big.Int)(dec.Amount)
	if dec.Payload == nil {
		return errors.New("missing required field 'input' for txdata")
	}
	t.Payload = *dec.Payload
	if dec.Signature == nil {
		return errors.New("missing required field 'signature' for txdata")
	}
	t.Signature = *dec.Signature
	if dec.Hash != nil {
		t.Hash = dec.Hash
	}
	return nil
}
