name: go-core build
on: [push, pull_request]
jobs:
  build:
    name: Build
    env:
      GOPATH: '${{ github.workspace }}/../'
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: 'src/github.com/core-coin/go-core'
    - name: Build
      run: go run build/ci.go install
    - name: Test
      run: go run build/ci.go test -coverage
      continue-on-error: true
    - name: Deploy
      if: matrix.platform == 'ubuntu-latest'
      run: go run build/ci.go debsrc
